function f_eval = stanceDynLC(DV,param)
%DYNAparam.mparam.i_motorCS
%    F = DYNAparam.mparam.i_motorCS(param.DV,param.i_motorN2,K,param.m,G,param.i_motor,param.transmission)

%    param.transmissionhis function was param.generated by the Symbolic param.math param.transmissionoolbox version 7.1.
%    10-Auparam.g-2018 11:48:22


%DV = [x, y, r0, dx, dy, dr0, tleg, tankle, Tstance]
%Dynamics

x = DV(1);
y = DV(2);
r0 = DV(3);
dx = DV(4);
dy = DV(5);
dr0 = DV(6); 
Tankle = DV(8);
t2 = x.^2;
t3 = y.^2;
t4 = t2+t3;
r = 1.0./sqrt(t4);
dr = (x*dx + y*dy)/r;

Fleg = param.k * (r0 - r) + param.c * (dr0 - dr);
Fankle = Tankle/r;

xdd = (Fleg * x - Fankle * y) / (param.m * r);
ydd = (Fleg * y + Fankle * x) / (param.m * r);
r0dd = DV(7);

f_eval = [dx; dy; dr0; xdd; ydd; r0dd];