function f_eval = stanceDyn(DV,param)
%DYNAparam.mparam.i_motorCS
%    F = DYNAparam.mparam.i_motorCS(param.DV,param.i_motorN2,K,param.m,G,param.i_motor,param.transmission)

%    param.transmissionhis function was param.generated by the Symbolic param.math param.transmissionoolbox version 7.1.
%    10-Auparam.g-2018 11:48:22


%DV = [x, y, r0, dx, dy, dr0, tleg, tankle, Tstance]
%Dynamics

    x = DV(1);
    y = DV(2);
    r0 = DV(3);
    dx = DV(4);
    dy = DV(5);
    dr0 = DV(6); 
    ddr0 = DV(7);
    Tankle = DV(8);
    r = sqrt(x.^2+y.^2);
    dr = (dx .* x + dy .* y) ./ r;

    Fleg = param.k * (r0 - r) + param.c * (dr0 - dr);
    Fankle = Tankle .* param.transmission_ankle ./ r;
    xcomp = x ./ r;
    ycomp = y ./ r;

    xdd = Fleg ./param.m  * xcomp - Fankle ./ param.m * ycomp;
    ydd = Fleg ./param.m  * ycomp - param.g + Fankle ./ param.m * xcomp;
    r0dd = ddr0;

    f_eval = [dx; dy; dr0; xdd; ydd; r0dd];
end